# Usually I wouldn't commit this file, but you can change your API keys here,
# should these keys get banned or blocked
FANART_TV_API_KEY: 3470f9905d5a82d9e91023bf3562a2eb
TMDB_API_KEY: a533c4925884599fa704aaf5a9006983
TVDB_API_KEY: C0BAA9786923CE73

# domains change a lot :/
EZTV_DOMAIN: eztv.ag
KICKASS_DOMAIN: kat.cr
