---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 25
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30
:queues:
- [often, 7]
- [analyze, 1]
- [default, 5]
- [seldom, 3]
- [transcode, 1]
:limits:
  transcode: 8
  analyze: 1
