---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 25
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 5
:queues:
- [scan, 1]
- [series_discovery, 7]
- [movies_discovery, 7]
- [analyze, 1]
- [default, 5]
- [transcode, 2]
:limits:
  transcode: 2
  analyze: 1
  scan: 1
  series_discovery: 1
  movies_discovery: 1
